In [20]:
import pandas as pd

MONTHLY_PATH = "../../data/final/economics_monthly.csv"
QUARTERLY_PATH = "../../data/final/economics_quarterly.csv"

RAW_DATA_FOLDER = "../../data/war"
ASSIGN_DATA_FOLDER = "../../data/assignment/ass1"

## MONTHLY DATASET

In [21]:
monthly_set = pd.read_csv(MONTHLY_PATH)

monthly_set["MonthlyDate"] = pd.to_datetime(monthly_set["MonthlyDate"]).dt.to_period("M")
start_period = pd.Period("2018-01", freq="M")
end_period = pd.Period("2026-08", freq="M")

filtered_monthly = monthly_set[monthly_set["MonthlyDate"].between(start_period, end_period)]

filtered_monthly

,MonthlyDate,InflationYOY,TRMAvg,OccupationRate,UnemploymentRate,PolicyRate,ColcapIndex,MonthlyReturn
762,2018-01,3.679528,2868.57,57.386400,12.137400,4.50,1558.18,2.941895
763,2018-02,3.372119,2860.25,57.833300,11.188200,4.50,1478.33,-5.124568
764,2018-03,3.139859,2847.93,58.733300,9.771600,4.50,1455.52,-1.542957
765,2018-04,3.127613,2766.29,59.837900,9.729200,4.25,1565.56,7.560185
766,2018-05,3.156785,2861.83,59.254100,9.979500,4.25,1546.71,-1.204042
...,...,...,...,...,...,...,...,...
861,2026-04,5.681310,3617.52,59.055998,8.781457,11.25,2178.00,-4.741494
862,2026-05,5.842080,3714.02,59.733833,8.020651,11.25,2176.90,-0.050505
863,2026-06,6.142750,3500.98,59.362215,8.026926,11.25,2269.08,4.234462
864,2026-07,6.026290,3268.95,59.519311,8.104578,12.00,2392.10,5.421581
865,2026-08,6.241690,3130.87,NaN,NaN,12.00,2425.08,1.378705

In [22]:
filtered_monthly.info()

<class 'pandas.DataFrame'>
RangeIndex: 104 entries, 762 to 865
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   MonthlyDate       104 non-null    period[M]
 1   InflationYOY      104 non-null    float64
 2   TRMAvg            104 non-null    float64
 3   OccupationRate    103 non-null    float64
 4   UnemploymentRate  103 non-null    float64
 5   PolicyRate        104 non-null    float64
 6   ColcapIndex       104 non-null    float64
 7   MonthlyReturn     104 non-null    float64
dtypes: float64(7), period[M](1)
memory usage: 6.6 KB

In [23]:
filtered_monthly.describe()

,InflationYOY,TRMAvg,OccupationRate,UnemploymentRate,PolicyRate,ColcapIndex,MonthlyReturn
count,104.000000,104.000000,103.000000,103.000000,104.000000,104.000000,104.000000
mean,5.807312,3777.216058,56.480649,11.292940,7.134615,1478.498365,0.637076
std,3.284086,492.568012,3.315927,2.907130,4.054232,319.285512,5.948536
min,1.489470,2766.290000,42.497100,7.024858,1.750000,1076.120000,-27.475300
25%,3.305927,3410.970000,55.681352,9.351905,4.250000,1250.195000,-2.530012
50%,5.131085,3825.480000,57.434633,10.631277,5.500000,1393.110000,1.207244
75%,7.227523,4051.945000,58.515750,12.129316,11.000000,1580.405000,4.018830
max,13.344330,4926.660000,60.172243,21.972000,13.250000,2474.760000,19.668667

In [24]:
filtered_monthly.to_csv(f"{ASSIGN_DATA_FOLDER}/economics_filtered_monthly.csv", index=False)

## QUARTERLY DATASET

In [25]:
quarterly_set = pd.read_csv(QUARTERLY_PATH)

start_quarter = "2018-Q1"
end_quarter = "2026-Q2"

filtered_quarteryly = quarterly_set[(quarterly_set['Quarter'] >= start_quarter) & (quarterly_set['Quarter'] <= end_quarter)]

filtered_quarteryly

    Quarter  RealGDPGrowth
48  2018-Q1           2.19
49  2018-Q2           2.33
50  2018-Q3           2.83
51  2018-Q4           2.90
52  2019-Q1           3.18
53  2019-Q2           3.39
54  2019-Q3           3.09
55  2019-Q4           3.08
56  2020-Q1           0.32
57  2020-Q2         -16.74
58  2020-Q3          -9.02
59  2020-Q4          -3.26
60  2021-Q1           1.78
61  2021-Q2          18.27
62  2021-Q3          13.52
63  2021-Q4          11.06
64  2022-Q1           7.68
65  2022-Q2          12.55
66  2022-Q3           7.37
67  2022-Q4           2.22
68  2023-Q1           2.67
69  2023-Q2           0.44
70  2023-Q3          -0.39
71  2023-Q4           0.68
72  2024-Q1           0.56
73  2024-Q2           1.21
74  2024-Q3           1.64
75  2024-Q4           2.57
76  2025-Q1           2.20
77  2025-Q2           2.28
78  2025-Q3           3.78
79  2025-Q4           2.03
80  2026-Q1           2.39
81  2026-Q2           3.37

In [26]:
filtered_quarteryly.info()

<class 'pandas.DataFrame'>
RangeIndex: 34 entries, 48 to 81
Data columns (total 2 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Quarter        34 non-null     str
 1   RealGDPGrowth  34 non-null     float64
dtypes: float64(1), str(1)
memory usage: 676.0 bytes

In [27]:
filtered_quarteryly.describe()

       RealGDPGrowth
count      34.000000
mean        2.769706
std         5.931705
min       -16.740000
25%         1.317500
50%         2.360000
75%         3.322500
max        18.270000

In [28]:
filtered_quarteryly.to_csv(f"{ASSIGN_DATA_FOLDER}/economics_filtered_quarteryly.csv", index=False)